### ISSUE TITLE
Crash when using `/fullplay` and no TAS is loaded

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#185]
Found by Lud
```
java.lang.IndexOutOfBoundsException:  1 
	at com.dselent.bigarraylist.BigArrayList.get(BigArrayList.java:1140) ~[BigArrayList.class:?]
	at com.dselent.bigarraylist.BigArrayList.get(BigArrayList.java:1175) ~[BigArrayList.class:?]
	at com.minecrafttas.tasmod.playback.PlaybackController.playbackNextTick(PlaybackController.java:418) ~[PlaybackController.class:?]
	at com.minecrafttas.tasmod.playback.PlaybackController.nextTick(PlaybackController.java:374) ~[PlaybackController.class:?]
	at net.minecraft.client.Minecraft.handler$zzi000$injectRunTickReturn(Minecraft.java:3550) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1913) ~[bib.class:?]
	at net.minecraft.client.Minecraft.redirect$zzi000$redirectRunTick(Minecraft.java:3398) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by PancakeTAS** [comment]
me when the exception are out of bounds array
